// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: edge/v1alpha1/edge_api.proto

package edgeconnect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	v1alpha1 "github.com/vinea-dev/gengo/edge/v1alpha1"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// EdgeAPIName is the fully-qualified name of the EdgeAPI service.
	EdgeAPIName = "edge.v1alpha1.EdgeAPI"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// EdgeAPIRegisterProcedure is the fully-qualified name of the EdgeAPI's Register RPC.
	EdgeAPIRegisterProcedure = "/edge.v1alpha1.EdgeAPI/Register"
	// EdgeAPISubscribeProcedure is the fully-qualified name of the EdgeAPI's Subscribe RPC.
	EdgeAPISubscribeProcedure = "/edge.v1alpha1.EdgeAPI/Subscribe"
)

// EdgeAPIClient is a client for the edge.v1alpha1.EdgeAPI service.
type EdgeAPIClient interface {
	// Register registers an agent with the server and returns a stream of
	// responses, starting with the agent's ID.
	Register(context.Context, *connect.Request[v1alpha1.RegisterRequest]) (*connect.ServerStreamForClient[v1alpha1.RegisterResponse], error)
	// Subscribe is a long-polling RPC for an agent to receive jobs from the
	// server. It waits until a job is available or the timeout is reached.
	Subscribe(context.Context, *connect.Request[v1alpha1.SubscribeRequest]) (*connect.Response[v1alpha1.SubscribeResponse], error)
}

// NewEdgeAPIClient constructs a client for the edge.v1alpha1.EdgeAPI service. By default, it uses
// the Connect protocol with the binary Protobuf Codec, asks for gzipped responses, and sends
// uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the connect.WithGRPC() or
// connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewEdgeAPIClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) EdgeAPIClient {
	baseURL = strings.TrimRight(baseURL, "/")
	edgeAPIMethods := v1alpha1.File_edge_v1alpha1_edge_api_proto.Services().ByName("EdgeAPI").Methods()
	return &edgeAPIClient{
		register: connect.NewClient[v1alpha1.RegisterRequest, v1alpha1.RegisterResponse](
			httpClient,
			baseURL+EdgeAPIRegisterProcedure,
			connect.WithSchema(edgeAPIMethods.ByName("Register")),
			connect.WithClientOptions(opts...),
		),
		subscribe: connect.NewClient[v1alpha1.SubscribeRequest, v1alpha1.SubscribeResponse](
			httpClient,
			baseURL+EdgeAPISubscribeProcedure,
			connect.WithSchema(edgeAPIMethods.ByName("Subscribe")),
			connect.WithClientOptions(opts...),
		),
	}
}

// edgeAPIClient implements EdgeAPIClient.
type edgeAPIClient struct {
	register  *connect.Client[v1alpha1.RegisterRequest, v1alpha1.RegisterResponse]
	subscribe *connect.Client[v1alpha1.SubscribeRequest, v1alpha1.SubscribeResponse]
}

// Register calls edge.v1alpha1.EdgeAPI.Register.
func (c *edgeAPIClient) Register(ctx context.Context, req *connect.Request[v1alpha1.RegisterRequest]) (*connect.ServerStreamForClient[v1alpha1.RegisterResponse], error) {
	return c.register.CallServerStream(ctx, req)
}

// Subscribe calls edge.v1alpha1.EdgeAPI.Subscribe.
func (c *edgeAPIClient) Subscribe(ctx context.Context, req *connect.Request[v1alpha1.SubscribeRequest]) (*connect.Response[v1alpha1.SubscribeResponse], error) {
	return c.subscribe.CallUnary(ctx, req)
}

// EdgeAPIHandler is an implementation of the edge.v1alpha1.EdgeAPI service.
type EdgeAPIHandler interface {
	// Register registers an agent with the server and returns a stream of
	// responses, starting with the agent's ID.
	Register(context.Context, *connect.Request[v1alpha1.RegisterRequest], *connect.ServerStream[v1alpha1.RegisterResponse]) error
	// Subscribe is a long-polling RPC for an agent to receive jobs from the
	// server. It waits until a job is available or the timeout is reached.
	Subscribe(context.Context, *connect.Request[v1alpha1.SubscribeRequest]) (*connect.Response[v1alpha1.SubscribeResponse], error)
}

// NewEdgeAPIHandler builds an HTTP handler from the service implementation. It returns the path on
// which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewEdgeAPIHandler(svc EdgeAPIHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	edgeAPIMethods := v1alpha1.File_edge_v1alpha1_edge_api_proto.Services().ByName("EdgeAPI").Methods()
	edgeAPIRegisterHandler := connect.NewServerStreamHandler(
		EdgeAPIRegisterProcedure,
		svc.Register,
		connect.WithSchema(edgeAPIMethods.ByName("Register")),
		connect.WithHandlerOptions(opts...),
	)
	edgeAPISubscribeHandler := connect.NewUnaryHandler(
		EdgeAPISubscribeProcedure,
		svc.Subscribe,
		connect.WithSchema(edgeAPIMethods.ByName("Subscribe")),
		connect.WithHandlerOptions(opts...),
	)
	return "/edge.v1alpha1.EdgeAPI/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case EdgeAPIRegisterProcedure:
			edgeAPIRegisterHandler.ServeHTTP(w, r)
		case EdgeAPISubscribeProcedure:
			edgeAPISubscribeHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedEdgeAPIHandler returns CodeUnimplemented from all methods.
type UnimplementedEdgeAPIHandler struct{}

func (UnimplementedEdgeAPIHandler) Register(context.Context, *connect.Request[v1alpha1.RegisterRequest], *connect.ServerStream[v1alpha1.RegisterResponse]) error {
	return connect.NewError(connect.CodeUnimplemented, errors.New("edge.v1alpha1.EdgeAPI.Register is not implemented"))
}

func (UnimplementedEdgeAPIHandler) Subscribe(context.Context, *connect.Request[v1alpha1.SubscribeRequest]) (*connect.Response[v1alpha1.SubscribeResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("edge.v1alpha1.EdgeAPI.Subscribe is not implemented"))
}
