// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        (unknown)
// source: foobar/v1alpha1/foobar.proto

package foobar

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// EchoRequest
type EchoRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// request id
	Id            string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EchoRequest) Reset() {
	*x = EchoRequest{}
	mi := &file_foobar_v1alpha1_foobar_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EchoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EchoRequest) ProtoMessage() {}

func (x *EchoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_foobar_v1alpha1_foobar_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EchoRequest.ProtoReflect.Descriptor instead.
func (*EchoRequest) Descriptor() ([]byte, []int) {
	return file_foobar_v1alpha1_foobar_proto_rawDescGZIP(), []int{0}
}

func (x *EchoRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

// EchoRequest
type EchoResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EchoResponse) Reset() {
	*x = EchoResponse{}
	mi := &file_foobar_v1alpha1_foobar_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EchoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EchoResponse) ProtoMessage() {}

func (x *EchoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_foobar_v1alpha1_foobar_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EchoResponse.ProtoReflect.Descriptor instead.
func (*EchoResponse) Descriptor() ([]byte, []int) {
	return file_foobar_v1alpha1_foobar_proto_rawDescGZIP(), []int{1}
}

var File_foobar_v1alpha1_foobar_proto protoreflect.FileDescriptor

const file_foobar_v1alpha1_foobar_proto_rawDesc = "" +
	"\n" +
	"\x1cfoobar/v1alpha1/foobar.proto\x12\x0ffoobar.v1alpha1\"\x1d\n" +
	"\vEchoRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\x0e\n" +
	"\fEchoResponse2R\n" +
	"\tFoobarAPI\x12E\n" +
	"\x04Echo\x12\x1c.foobar.v1alpha1.EchoRequest\x1a\x1d.foobar.v1alpha1.EchoResponse\"\x00B5P\x01Z1github.com/vinea-dev/gengo/foobar/v1alpha1;foobarb\x06proto3"

var (
	file_foobar_v1alpha1_foobar_proto_rawDescOnce sync.Once
	file_foobar_v1alpha1_foobar_proto_rawDescData []byte
)

func file_foobar_v1alpha1_foobar_proto_rawDescGZIP() []byte {
	file_foobar_v1alpha1_foobar_proto_rawDescOnce.Do(func() {
		file_foobar_v1alpha1_foobar_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_foobar_v1alpha1_foobar_proto_rawDesc), len(file_foobar_v1alpha1_foobar_proto_rawDesc)))
	})
	return file_foobar_v1alpha1_foobar_proto_rawDescData
}

var file_foobar_v1alpha1_foobar_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_foobar_v1alpha1_foobar_proto_goTypes = []any{
	(*EchoRequest)(nil),  // 0: foobar.v1alpha1.EchoRequest
	(*EchoResponse)(nil), // 1: foobar.v1alpha1.EchoResponse
}
var file_foobar_v1alpha1_foobar_proto_depIdxs = []int32{
	0, // 0: foobar.v1alpha1.FoobarAPI.Echo:input_type -> foobar.v1alpha1.EchoRequest
	1, // 1: foobar.v1alpha1.FoobarAPI.Echo:output_type -> foobar.v1alpha1.EchoResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_foobar_v1alpha1_foobar_proto_init() }
func file_foobar_v1alpha1_foobar_proto_init() {
	if File_foobar_v1alpha1_foobar_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_foobar_v1alpha1_foobar_proto_rawDesc), len(file_foobar_v1alpha1_foobar_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_foobar_v1alpha1_foobar_proto_goTypes,
		DependencyIndexes: file_foobar_v1alpha1_foobar_proto_depIdxs,
		MessageInfos:      file_foobar_v1alpha1_foobar_proto_msgTypes,
	}.Build()
	File_foobar_v1alpha1_foobar_proto = out.File
	file_foobar_v1alpha1_foobar_proto_goTypes = nil
	file_foobar_v1alpha1_foobar_proto_depIdxs = nil
}
