// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             (unknown)
// source: foobar/v1alpha1/foobar.proto

package foobar

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	FoobarAPI_Echo_FullMethodName = "/foobar.v1alpha1.FoobarAPI/Echo"
)

// FoobarAPIClient is the client API for FoobarAPI service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// FoobarAPI
type FoobarAPIClient interface {
	// comments.
	Echo(ctx context.Context, in *EchoRequest, opts ...grpc.CallOption) (*EchoResponse, error)
}

type foobarAPIClient struct {
	cc grpc.ClientConnInterface
}

func NewFoobarAPIClient(cc grpc.ClientConnInterface) FoobarAPIClient {
	return &foobarAPIClient{cc}
}

func (c *foobarAPIClient) Echo(ctx context.Context, in *EchoRequest, opts ...grpc.CallOption) (*EchoResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EchoResponse)
	err := c.cc.Invoke(ctx, FoobarAPI_Echo_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// FoobarAPIServer is the server API for FoobarAPI service.
// All implementations should embed UnimplementedFoobarAPIServer
// for forward compatibility.
//
// FoobarAPI
type FoobarAPIServer interface {
	// comments.
	Echo(context.Context, *EchoRequest) (*EchoResponse, error)
}

// UnimplementedFoobarAPIServer should be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedFoobarAPIServer struct{}

func (UnimplementedFoobarAPIServer) Echo(context.Context, *EchoRequest) (*EchoResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Echo not implemented")
}
func (UnimplementedFoobarAPIServer) testEmbeddedByValue() {}

// UnsafeFoobarAPIServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to FoobarAPIServer will
// result in compilation errors.
type UnsafeFoobarAPIServer interface {
	mustEmbedUnimplementedFoobarAPIServer()
}

func RegisterFoobarAPIServer(s grpc.ServiceRegistrar, srv FoobarAPIServer) {
	// If the following call pancis, it indicates UnimplementedFoobarAPIServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&FoobarAPI_ServiceDesc, srv)
}

func _FoobarAPI_Echo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EchoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FoobarAPIServer).Echo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FoobarAPI_Echo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FoobarAPIServer).Echo(ctx, req.(*EchoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// FoobarAPI_ServiceDesc is the grpc.ServiceDesc for FoobarAPI service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var FoobarAPI_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "foobar.v1alpha1.FoobarAPI",
	HandlerType: (*FoobarAPIServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Echo",
			Handler:    _FoobarAPI_Echo_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "foobar/v1alpha1/foobar.proto",
}
