// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: foobar/v1alpha1/foobar.proto

package foobarconnect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	v1alpha1 "github.com/vinea-dev/gengo/foobar/v1alpha1"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// FoobarAPIName is the fully-qualified name of the FoobarAPI service.
	FoobarAPIName = "foobar.v1alpha1.FoobarAPI"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// FoobarAPIEchoProcedure is the fully-qualified name of the FoobarAPI's Echo RPC.
	FoobarAPIEchoProcedure = "/foobar.v1alpha1.FoobarAPI/Echo"
)

// FoobarAPIClient is a client for the foobar.v1alpha1.FoobarAPI service.
type FoobarAPIClient interface {
	// Echo is a simple RPC that echoes the request ID in the response,
	// along with a message.
	Echo(context.Context, *connect.Request[v1alpha1.EchoRequest]) (*connect.Response[v1alpha1.EchoResponse], error)
}

// NewFoobarAPIClient constructs a client for the foobar.v1alpha1.FoobarAPI service. By default, it
// uses the Connect protocol with the binary Protobuf Codec, asks for gzipped responses, and sends
// uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the connect.WithGRPC() or
// connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewFoobarAPIClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) FoobarAPIClient {
	baseURL = strings.TrimRight(baseURL, "/")
	foobarAPIMethods := v1alpha1.File_foobar_v1alpha1_foobar_proto.Services().ByName("FoobarAPI").Methods()
	return &foobarAPIClient{
		echo: connect.NewClient[v1alpha1.EchoRequest, v1alpha1.EchoResponse](
			httpClient,
			baseURL+FoobarAPIEchoProcedure,
			connect.WithSchema(foobarAPIMethods.ByName("Echo")),
			connect.WithClientOptions(opts...),
		),
	}
}

// foobarAPIClient implements FoobarAPIClient.
type foobarAPIClient struct {
	echo *connect.Client[v1alpha1.EchoRequest, v1alpha1.EchoResponse]
}

// Echo calls foobar.v1alpha1.FoobarAPI.Echo.
func (c *foobarAPIClient) Echo(ctx context.Context, req *connect.Request[v1alpha1.EchoRequest]) (*connect.Response[v1alpha1.EchoResponse], error) {
	return c.echo.CallUnary(ctx, req)
}

// FoobarAPIHandler is an implementation of the foobar.v1alpha1.FoobarAPI service.
type FoobarAPIHandler interface {
	// Echo is a simple RPC that echoes the request ID in the response,
	// along with a message.
	Echo(context.Context, *connect.Request[v1alpha1.EchoRequest]) (*connect.Response[v1alpha1.EchoResponse], error)
}

// NewFoobarAPIHandler builds an HTTP handler from the service implementation. It returns the path
// on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewFoobarAPIHandler(svc FoobarAPIHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	foobarAPIMethods := v1alpha1.File_foobar_v1alpha1_foobar_proto.Services().ByName("FoobarAPI").Methods()
	foobarAPIEchoHandler := connect.NewUnaryHandler(
		FoobarAPIEchoProcedure,
		svc.Echo,
		connect.WithSchema(foobarAPIMethods.ByName("Echo")),
		connect.WithHandlerOptions(opts...),
	)
	return "/foobar.v1alpha1.FoobarAPI/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case FoobarAPIEchoProcedure:
			foobarAPIEchoHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedFoobarAPIHandler returns CodeUnimplemented from all methods.
type UnimplementedFoobarAPIHandler struct{}

func (UnimplementedFoobarAPIHandler) Echo(context.Context, *connect.Request[v1alpha1.EchoRequest]) (*connect.Response[v1alpha1.EchoResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("foobar.v1alpha1.FoobarAPI.Echo is not implemented"))
}
