// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             (unknown)
// source: edge/v1alpha1/edge_api.proto

package edge

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	EdgeAPI_Register_FullMethodName  = "/edge.v1alpha1.EdgeAPI/Register"
	EdgeAPI_Subscribe_FullMethodName = "/edge.v1alpha1.EdgeAPI/Subscribe"
)

// EdgeAPIClient is the client API for EdgeAPI service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// EdgeAPI is a service for edge devices to connect and receive jobs.
type EdgeAPIClient interface {
	// Register registers an agent with the server and returns a stream of
	// responses, starting with the agent's ID.
	Register(ctx context.Context, in *RegisterRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[RegisterResponse], error)
	// Subscribe is a long-polling RPC for an agent to receive jobs from the
	// server. It waits until a job is available or the timeout is reached.
	Subscribe(ctx context.Context, in *SubscribeRequest, opts ...grpc.CallOption) (*SubscribeResponse, error)
}

type edgeAPIClient struct {
	cc grpc.ClientConnInterface
}

func NewEdgeAPIClient(cc grpc.ClientConnInterface) EdgeAPIClient {
	return &edgeAPIClient{cc}
}

func (c *edgeAPIClient) Register(ctx context.Context, in *RegisterRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[RegisterResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &EdgeAPI_ServiceDesc.Streams[0], EdgeAPI_Register_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[RegisterRequest, RegisterResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type EdgeAPI_RegisterClient = grpc.ServerStreamingClient[RegisterResponse]

func (c *edgeAPIClient) Subscribe(ctx context.Context, in *SubscribeRequest, opts ...grpc.CallOption) (*SubscribeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SubscribeResponse)
	err := c.cc.Invoke(ctx, EdgeAPI_Subscribe_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// EdgeAPIServer is the server API for EdgeAPI service.
// All implementations should embed UnimplementedEdgeAPIServer
// for forward compatibility.
//
// EdgeAPI is a service for edge devices to connect and receive jobs.
type EdgeAPIServer interface {
	// Register registers an agent with the server and returns a stream of
	// responses, starting with the agent's ID.
	Register(*RegisterRequest, grpc.ServerStreamingServer[RegisterResponse]) error
	// Subscribe is a long-polling RPC for an agent to receive jobs from the
	// server. It waits until a job is available or the timeout is reached.
	Subscribe(context.Context, *SubscribeRequest) (*SubscribeResponse, error)
}

// UnimplementedEdgeAPIServer should be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedEdgeAPIServer struct{}

func (UnimplementedEdgeAPIServer) Register(*RegisterRequest, grpc.ServerStreamingServer[RegisterResponse]) error {
	return status.Errorf(codes.Unimplemented, "method Register not implemented")
}
func (UnimplementedEdgeAPIServer) Subscribe(context.Context, *SubscribeRequest) (*SubscribeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Subscribe not implemented")
}
func (UnimplementedEdgeAPIServer) testEmbeddedByValue() {}

// UnsafeEdgeAPIServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to EdgeAPIServer will
// result in compilation errors.
type UnsafeEdgeAPIServer interface {
	mustEmbedUnimplementedEdgeAPIServer()
}

func RegisterEdgeAPIServer(s grpc.ServiceRegistrar, srv EdgeAPIServer) {
	// If the following call pancis, it indicates UnimplementedEdgeAPIServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&EdgeAPI_ServiceDesc, srv)
}

func _EdgeAPI_Register_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(RegisterRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(EdgeAPIServer).Register(m, &grpc.GenericServerStream[RegisterRequest, RegisterResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type EdgeAPI_RegisterServer = grpc.ServerStreamingServer[RegisterResponse]

func _EdgeAPI_Subscribe_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SubscribeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EdgeAPIServer).Subscribe(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EdgeAPI_Subscribe_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EdgeAPIServer).Subscribe(ctx, req.(*SubscribeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// EdgeAPI_ServiceDesc is the grpc.ServiceDesc for EdgeAPI service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var EdgeAPI_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "edge.v1alpha1.EdgeAPI",
	HandlerType: (*EdgeAPIServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Subscribe",
			Handler:    _EdgeAPI_Subscribe_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Register",
			Handler:       _EdgeAPI_Register_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "edge/v1alpha1/edge_api.proto",
}
