// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        (unknown)
// source: edge/v1alpha1/edge_api.proto

package edge

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	durationpb "google.golang.org/protobuf/types/known/durationpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// JobType defines the different types of jobs that can be assigned.
type JobType int32

const (
	// JOB_TYPE_UNSPECIFIED is the default, unknown job type.
	JobType_JOB_TYPE_UNSPECIFIED JobType = 0
	// JOB_TYPE_SCHEDULED is a job that is scheduled to run at a specific time
	// or interval.
	JobType_JOB_TYPE_SCHEDULED JobType = 1
)

// Enum value maps for JobType.
var (
	JobType_name = map[int32]string{
		0: "JOB_TYPE_UNSPECIFIED",
		1: "JOB_TYPE_SCHEDULED",
	}
	JobType_value = map[string]int32{
		"JOB_TYPE_UNSPECIFIED": 0,
		"JOB_TYPE_SCHEDULED":   1,
	}
)

func (x JobType) Enum() *JobType {
	p := new(JobType)
	*p = x
	return p
}

func (x JobType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (JobType) Descriptor() protoreflect.EnumDescriptor {
	return file_edge_v1alpha1_edge_api_proto_enumTypes[0].Descriptor()
}

func (JobType) Type() protoreflect.EnumType {
	return &file_edge_v1alpha1_edge_api_proto_enumTypes[0]
}

func (x JobType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use JobType.Descriptor instead.
func (JobType) EnumDescriptor() ([]byte, []int) {
	return file_edge_v1alpha1_edge_api_proto_rawDescGZIP(), []int{0}
}

// RegisterRequest is the request message for the Register RPC.
type RegisterRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// device_fingerprint is a unique identifier for the device registering.
	DeviceFingerprint string `protobuf:"bytes,1,opt,name=device_fingerprint,json=deviceFingerprint,proto3" json:"device_fingerprint,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *RegisterRequest) Reset() {
	*x = RegisterRequest{}
	mi := &file_edge_v1alpha1_edge_api_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterRequest) ProtoMessage() {}

func (x *RegisterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_edge_v1alpha1_edge_api_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterRequest.ProtoReflect.Descriptor instead.
func (*RegisterRequest) Descriptor() ([]byte, []int) {
	return file_edge_v1alpha1_edge_api_proto_rawDescGZIP(), []int{0}
}

func (x *RegisterRequest) GetDeviceFingerprint() string {
	if x != nil {
		return x.DeviceFingerprint
	}
	return ""
}

// RegisterResponse is the response message for the Register RPC.
type RegisterResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// id is the unique identifier assigned to the agent by the server.
	Id            string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterResponse) Reset() {
	*x = RegisterResponse{}
	mi := &file_edge_v1alpha1_edge_api_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterResponse) ProtoMessage() {}

func (x *RegisterResponse) ProtoReflect() protoreflect.Message {
	mi := &file_edge_v1alpha1_edge_api_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterResponse.ProtoReflect.Descriptor instead.
func (*RegisterResponse) Descriptor() ([]byte, []int) {
	return file_edge_v1alpha1_edge_api_proto_rawDescGZIP(), []int{1}
}

func (x *RegisterResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

// SubscribeRequest is the request message for the Subscribe RPC.
type SubscribeRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// agent_id is the unique identifier of the agent that is subscribing.
	AgentId string `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	// timeout is the maximum duration the server should wait for a job before
	// responding.
	Timeout       *durationpb.Duration `protobuf:"bytes,2,opt,name=timeout,proto3" json:"timeout,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubscribeRequest) Reset() {
	*x = SubscribeRequest{}
	mi := &file_edge_v1alpha1_edge_api_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubscribeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubscribeRequest) ProtoMessage() {}

func (x *SubscribeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_edge_v1alpha1_edge_api_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubscribeRequest.ProtoReflect.Descriptor instead.
func (*SubscribeRequest) Descriptor() ([]byte, []int) {
	return file_edge_v1alpha1_edge_api_proto_rawDescGZIP(), []int{2}
}

func (x *SubscribeRequest) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *SubscribeRequest) GetTimeout() *durationpb.Duration {
	if x != nil {
		return x.Timeout
	}
	return nil
}

// SubscribeResponse is the response message for the Subscribe RPC, containing
// job details.
type SubscribeResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// job_id is the unique identifier for the received job.
	JobId string `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	// job_describe is a description of the job.
	JobDescribe string `protobuf:"bytes,2,opt,name=job_describe,json=jobDescribe,proto3" json:"job_describe,omitempty"`
	// job_type is the type of the job.
	JobType       JobType `protobuf:"varint,3,opt,name=job_type,json=jobType,proto3,enum=edge.v1alpha1.JobType" json:"job_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubscribeResponse) Reset() {
	*x = SubscribeResponse{}
	mi := &file_edge_v1alpha1_edge_api_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubscribeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubscribeResponse) ProtoMessage() {}

func (x *SubscribeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_edge_v1alpha1_edge_api_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubscribeResponse.ProtoReflect.Descriptor instead.
func (*SubscribeResponse) Descriptor() ([]byte, []int) {
	return file_edge_v1alpha1_edge_api_proto_rawDescGZIP(), []int{3}
}

func (x *SubscribeResponse) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

func (x *SubscribeResponse) GetJobDescribe() string {
	if x != nil {
		return x.JobDescribe
	}
	return ""
}

func (x *SubscribeResponse) GetJobType() JobType {
	if x != nil {
		return x.JobType
	}
	return JobType_JOB_TYPE_UNSPECIFIED
}

var File_edge_v1alpha1_edge_api_proto protoreflect.FileDescriptor

const file_edge_v1alpha1_edge_api_proto_rawDesc = "" +
	"\n" +
	"\x1cedge/v1alpha1/edge_api.proto\x12\redge.v1alpha1\x1a\x1egoogle/protobuf/duration.proto\"@\n" +
	"\x0fRegisterRequest\x12-\n" +
	"\x12device_fingerprint\x18\x01 \x01(\tR\x11deviceFingerprint\"\"\n" +
	"\x10RegisterResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"b\n" +
	"\x10SubscribeRequest\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\tR\aagentId\x123\n" +
	"\atimeout\x18\x02 \x01(\v2\x19.google.protobuf.DurationR\atimeout\"\x80\x01\n" +
	"\x11SubscribeResponse\x12\x15\n" +
	"\x06job_id\x18\x01 \x01(\tR\x05jobId\x12!\n" +
	"\fjob_describe\x18\x02 \x01(\tR\vjobDescribe\x121\n" +
	"\bjob_type\x18\x03 \x01(\x0e2\x16.edge.v1alpha1.JobTypeR\ajobType*;\n" +
	"\aJobType\x12\x18\n" +
	"\x14JOB_TYPE_UNSPECIFIED\x10\x00\x12\x16\n" +
	"\x12JOB_TYPE_SCHEDULED\x10\x012\xac\x01\n" +
	"\aEdgeAPI\x12O\n" +
	"\bRegister\x12\x1e.edge.v1alpha1.RegisterRequest\x1a\x1f.edge.v1alpha1.RegisterResponse\"\x000\x01\x12P\n" +
	"\tSubscribe\x12\x1f.edge.v1alpha1.SubscribeRequest\x1a .edge.v1alpha1.SubscribeResponse\"\x00B1P\x01Z-github.com/vinea-dev/gengo/edge/v1alpha1;edgeb\x06proto3"

var (
	file_edge_v1alpha1_edge_api_proto_rawDescOnce sync.Once
	file_edge_v1alpha1_edge_api_proto_rawDescData []byte
)

func file_edge_v1alpha1_edge_api_proto_rawDescGZIP() []byte {
	file_edge_v1alpha1_edge_api_proto_rawDescOnce.Do(func() {
		file_edge_v1alpha1_edge_api_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_edge_v1alpha1_edge_api_proto_rawDesc), len(file_edge_v1alpha1_edge_api_proto_rawDesc)))
	})
	return file_edge_v1alpha1_edge_api_proto_rawDescData
}

var file_edge_v1alpha1_edge_api_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_edge_v1alpha1_edge_api_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_edge_v1alpha1_edge_api_proto_goTypes = []any{
	(JobType)(0),                // 0: edge.v1alpha1.JobType
	(*RegisterRequest)(nil),     // 1: edge.v1alpha1.RegisterRequest
	(*RegisterResponse)(nil),    // 2: edge.v1alpha1.RegisterResponse
	(*SubscribeRequest)(nil),    // 3: edge.v1alpha1.SubscribeRequest
	(*SubscribeResponse)(nil),   // 4: edge.v1alpha1.SubscribeResponse
	(*durationpb.Duration)(nil), // 5: google.protobuf.Duration
}
var file_edge_v1alpha1_edge_api_proto_depIdxs = []int32{
	5, // 0: edge.v1alpha1.SubscribeRequest.timeout:type_name -> google.protobuf.Duration
	0, // 1: edge.v1alpha1.SubscribeResponse.job_type:type_name -> edge.v1alpha1.JobType
	1, // 2: edge.v1alpha1.EdgeAPI.Register:input_type -> edge.v1alpha1.RegisterRequest
	3, // 3: edge.v1alpha1.EdgeAPI.Subscribe:input_type -> edge.v1alpha1.SubscribeRequest
	2, // 4: edge.v1alpha1.EdgeAPI.Register:output_type -> edge.v1alpha1.RegisterResponse
	4, // 5: edge.v1alpha1.EdgeAPI.Subscribe:output_type -> edge.v1alpha1.SubscribeResponse
	4, // [4:6] is the sub-list for method output_type
	2, // [2:4] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_edge_v1alpha1_edge_api_proto_init() }
func file_edge_v1alpha1_edge_api_proto_init() {
	if File_edge_v1alpha1_edge_api_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_edge_v1alpha1_edge_api_proto_rawDesc), len(file_edge_v1alpha1_edge_api_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_edge_v1alpha1_edge_api_proto_goTypes,
		DependencyIndexes: file_edge_v1alpha1_edge_api_proto_depIdxs,
		EnumInfos:         file_edge_v1alpha1_edge_api_proto_enumTypes,
		MessageInfos:      file_edge_v1alpha1_edge_api_proto_msgTypes,
	}.Build()
	File_edge_v1alpha1_edge_api_proto = out.File
	file_edge_v1alpha1_edge_api_proto_goTypes = nil
	file_edge_v1alpha1_edge_api_proto_depIdxs = nil
}
